server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

paypal:
  mode: sandbox

logging:
  level:
    com.motorpoint: INFO
    org.springframework: WARN

cors:
  allowed-origins: ${CORS_ORIGINS}