server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

paypal:
  mode: live
  api-url: https://api-m.paypal.com

logging:
  level:
    root: INFO
    com.motorpoint: INFO
    org.springframework: WARN

cors:
  allowed-origins: ${CORS_ORIGINS}

management:
  endpoints:
    web:
      exposure:
        include: health, info